version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: rundb
      POSTGRES_USER: run
      POSTGRES_PASSWORD: running

  backend:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    command: sh -c "cd runapp_frontend && yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
