# Generated by Django 3.2.7 on 2023-07-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('admin_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=20)),
                ('distance_value', models.FloatField(blank=True, null=True)),
                ('distance_unit', models.CharField(blank=True, choices=[('km', 'km'), ('mile', 'mile'), ('m', 'm')], max_length=5, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, choices=[('800m', '800m'), ('1500m', '1500m'), ('1mile', '1mile'), ('3000m', '3000m'), ('3000mSC', '3000mSC'), ('2mile', '2mile'), ('5000m', '5000m'), ('10000m', '10000m'), ('ハーフマラソン', 'ハーフマラソン'), ('フルマラソン', 'フルマラソン')], max_length=20, null=True)),
                ('best_time', models.CharField(blank=True, help_text='Time in the format hh:mm:ss:SS', max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runcalc.user')),
            ],
        ),
    ]
